name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint --fix

      - name: Test
        run: yarn test -u --ci --coverage --maxWorkers=2
        env:
          API_KEY: '1d6c5c07-fdeb-4c86-b6b6-56b88eaa67dc.0.de986a66-4ddc-4b6e-b353-6b2e3381d46b.kmJPPMMSo5ELMDpCWKaX2it5k55qVn7QM6iwWZ5NBwN'
          TEST_DELTA_STORAGE_SERVER_HOST: https://staging-api.delta.storage
      - name: Build
        run: yarn build
